### ISSUE TITLE
How to include alongside `rmwc` in project?

### ISSUE THREAD

**Issue by andrewhao** [ncknt/rmwc-typed#7]
Hi there,

I'm having trouble figuring out how to include this in my `tsconfig.json` for my third party project. I can't just directly check this out as a package into `node_modules` since the `node_modules` directory is excluded from my `tsconfig.json`. For example, my package.json has:

```js
  "devDependencies": {
    "@types/jest": "^22.2.0",
    "@types/node": "^9.4.6",
    "@types/react": "^16.0.40",
    "@types/react-dom": "^16.0.4",
    "prettier": "^1.11.1",
    "typescript": "^2.7.2",
    "rmwc-typed": "ncknt/rmwc-typed"
  }
```

And in my app:

```
import {
  Toolbar,
  ToolbarRow,
  ToolbarTitle
} from "rmwc";
```

Gives the error 

```
[ts]
Could not find a declaration file for module 'rmwc'. '/Users/andrewhao/personal/dashy/node_modules/rmwc/index.js' implicitly has an 'any' type.
  Try `npm install @types/rmwc` if it exists or add a new declaration (.d.ts) file containing `declare module 'rmwc';
```

Any tips on how to wire up these types in my app?

**Comment by UFOMelkor** [comment]
I'm new to typescript, but I would guess it is not found because it is not installed within the types root (see http://www.typescriptlang.org/docs/handbook/tsconfig-json.html). You can configure your type root or change the alias to `@types/rmwc`.

**Comment by ncknt** [comment]
Add the following to your package.json:
`
 "devDependencies": {
    "@types/rmwc": "ncknt/rmwc-typed"
  }`

As you may have noticed, the bindings are quite out of date though so while it may still help you get started, the project needs more work.

**Comment by rachel-church** [comment]
The line `import { Menu } from 'rmwc/Menu';` still gives me the error `Could not find a declaration file for module 'rmwc'`.

My `tsconfig.json` file has`"typeRoots": ["./node_modules/@types"]`. Is there any other change I need to make to make TS able to find `@types/rmwc/Menu`?
